config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'folders#index'

  resources :company, only: [:show]
  resources :permissions, only: [:create, :destroy, :index]
  resources :comments, only: [:index, :create]
  
  resources :folders do
    resources :documents
  end
  
  delete 'delete_user/:id' => 'users#delete',        as: :delete_user
  get    'dashboard'       => 'dashboard#dashboard', as: :dashboard
  get    'settings'        => 'dashboard#settings',  as: :settings
  get    'users'           => 'users#index',         as: :users

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :load_activities, only: [:dashboard]
  respond_to :html, :js
  
  def dashboard
    unless current_user.admin?
      redirect_to folders_path
    end
    @documents = @company.documents.order('updated_at DESC')
  end

  def settings
  end

  private
    def load_activities
      if current_user && current_user.admin?
        @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
      end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dashboard.html.erb
<h1>Dashboard</h1>

app/views/dashboard/_user_edit_form.html.erb
    <div class="well users-edit">

    <h4 class="text-center">Edit Profile Information</h4>

    <%= form_for(resource, url: registration_path(resource), html: { method: :put }) do |f| %>

      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, class: "form-control" %>
      </div>

      <% if false #devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
      <% end %>

      <div class="form-group">
        <%= f.label :password, "New password" %> <i>(leave blank if you don't want to change it)</i><br />
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm new password" %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
        <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <h5>Cancel my account</h5>

    <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-default" %></p>

    <%= link_to "Back", :back %>
    </div>

app/views/dashboard/dashboard.html.erb
<div class="row">
  <div class="col-sm-6">
  <!-- Users section -->
    <div class="users-section">
      <p class="permissions-link"><%= link_to 'Manage Users', users_path %></p>
      <h3>Users</h3>
        <ul class="list-group">
        <% @users.each do |user| %>
          <% unless user == current_user %>
            <li class="list-group-item"><span class="user-name"><%= user.first_name %> <%= user.last_name %></span> <span class="user-position"><%= user.position %></span></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <!-- Company Details -->
    <h3><%= @company.name %></h3>
    <ul class="list-group">
      <li class="list-group-item">Address: <%= @company.address %></li>
      <li class="list-group-item">Phone: <%= @company.phone_number %></li>
      <li class="list-group-item">City: <%= @company.city %></li>
      <li class="list-group-item">Country: <%= @company.country %></li>
      <li class="list-group-item">Description: <%= @company.description %></li>
      <li class="list-group-item">Tin Number: <%= @company.tin %></li>
    </ul>

    
  </div>

  <!-- Recent Activity -->
  <div class="col-sm-6" id="activity-feed">
    <h3>Recent Activity</h3>
    <%= render 'shared/activities' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/index.js.erb
$('#content').html("<%= j (render 'dashboard') %>");

app/views/dashboard/settings.html.erb
<div class="row" id="settings-row">
<!-- Left use info panel -->
  <div class="col-sm-4" id="user-info">
    <div class="text-center">
      <% if current_user.avatar.present? %>
        <%= image_tag current_user.avatar.url(:small) %>
      <% else %>
        <%= image_tag 'avatars/small/avatar_default.jpg' %>
      <% end %>
      <h4><%= "#{current_user.first_name} #{current_user.last_name}" %></h4>
      <p><%= current_user.position %></p>
      <ul class="list-group">
        <li class="list-group-item"><%= current_user.email %></li>
        <li class="list-group-item">Joined: <%= current_user.created_at.strftime('%B %-d, %Y') %></li>
        <li class="list-group-item">Last login: <%= current_user.last_sign_in_at.strftime('%B %-d, %Y') %></li>
      </ul>
    </div>

    <div>

    </div>
      <h3><%= @company.name %></h3>
     <%= render 'company/company_edit_form' %>
  </div>

<!-- Main panel for settings -->
  <div class="col-sm-8" id="user-settings">
    <!-- Form for editing user information -->
    <%= render 'dashboard/user_edit_form', resource: current_user %>
    <!-- Other settings like notifications, etc. -->
  </div>
</div>