config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'folders#index'

  resources :company, only: [:show]
  resources :permissions, only: [:create, :destroy, :index]
  resources :comments, only: [:index, :create]
  
  resources :folders do
    resources :documents
  end
  
  delete 'delete_user/:id' => 'users#delete',        as: :delete_user
  get    'dashboard'       => 'dashboard#dashboard', as: :dashboard
  get    'settings'        => 'dashboard#settings',  as: :settings
  get    'users'           => 'users#index',         as: :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Make confirmable?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company
  has_many :permissions
  has_many :comments
  has_attached_file :avatar
  validates_attachment :avatar,
      default_url: "avatars/:style/avatar_default.jpg",
      styles: { thumb: "100x100#", small: "150x150#", medium: "300x300#"},
      content_type: { content_type: [
        "image/jpg", "image/jpeg", "image/png", "image/gif"]},
      message: "Sorry, only png, gif, jpeg or jpg."
      
  

  enum role: [:normal, :admin]

  # For permissions, user should have attribute to hold folder ids that can be accessed
  # Maybe admins have a value of 0 for full access of folders?
  def can_access?(resource)
    resource.can_be_accessed_by?(self)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_admin

  def index
    @permission = Permission.new
  end

  def delete
    @user = @users.find(params[:id])
    @user.destroy
    if @user.destroy 
      redirect_to users_path, notice: "User deleted"
    end
  end

  private

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1 class=text-center>Manage Users</h1>
<div class="row">
  <div class="col-md-4 users">
    <h3 class="text-center">Users</h3>
    <ul class="list-group">
      <% @users.each do |user| %>
        <% unless user == current_user %>
          <li class="list-group-item">
          <span class="glyphicon glyphicon-user user-icon"></span> <%= "#{user.first_name} #{user.last_name}" %>
            <%= link_to 'Delete User', delete_user_path(user), method: :delete, data: { confirm: "Are you sure?"}, class: "delete-user-button" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>


  <!-- List has to be fixed, its not properly nested atm -->
  <div class="col-md-8">
    <div id="permissions">
      <%= render 'permissions/permissions', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- If current_user.admin? -->
<div class="col-md-3">
  <div class="well text-center">
    <h3><%= "#{current_user.first_name} #{current_user.last_name}" %></h3>
    <% image_tag current_user.avatar.url(:thumb) %>

  </div>
</div>
<div class="col-md-9">
  <ul>
    <% @users.each do |user| %>
      <li><%= "#{user.first_name} #{user.last_name}" %></li>
    <% end %>
  </ul>
</div>
<!-- else -->