config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'folders#index'

  resources :company, only: [:show]
  resources :permissions, only: [:create, :destroy, :index]
  resources :comments, only: [:index, :create]
  
  resources :folders do
    resources :documents
  end
  
  delete 'delete_user/:id' => 'users#delete',        as: :delete_user
  get    'dashboard'       => 'dashboard#dashboard', as: :dashboard
  get    'settings'        => 'dashboard#settings',  as: :settings
  get    'users'           => 'users#index',         as: :users

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :folder
  has_attached_file :file
  validates_attachment :file,
      styles: { thumb: "100x100#", small: "150x150#"},
      content_type: { content_type: [
        "application/pdf", "application/xls", "application/xlsx", 
        "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
        "application/msword", "application/doc",  
        "text/plain", "text/csv"]},
      message: "Sorry, only PDF, Excel, MSWord or plain text files are allowed."

  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user }

  def file_format
    content_type = self.file_content_type
    if content_type.include?("xlsx")
      return "xlsx"
    elsif content_type.include?("xls") || content_type.include?("excel")
      return "xls"
    elsif content_type.include?("spreadsheetml")
      return "ods"
    elsif content_type.include?("pdf")
      return "pdf"
    elsif content_type.include?("doc") || content_type.include?("msword")
      return "doc"
    elsif content_type.include?("text/plain") || content_type.include?("file/text")
      return "txt"
    elsif content_file = nil
      return "nil"
    end
  end

  def doc_or_spreadsheet?
    content_type = self.file_content_type
    if content_type.include?("xlsx") || content_type.include?("xls") || content_type.include?("excel") || content_type.include?("spreadsheetml") || content_type.include?("doc") || content_type.include?("msword")
      true
    else
      false
    end
  end

  # Permissions
  def can_be_accessed_by?(user)
    # the parent folder should have an attribute to track permitted users
    self.folder.can_be_accessed_by?(user)
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :correct_folder_and_documents, only: [:index, :create, :destroy, :edit]
  before_action :apikey
  respond_to :html, :js

  def index
    @document = @documents.build
  end

  def create
    @document = @folder.documents.build(document_params)
    @document.save
    respond_to do |format|
      # flash.now[:success] = "File successfuly uploaded!"
      format.html { redirect_to controller: 'folders', action: 'index', remote: true, folder: @folder }
      format.js {}
    end
  end

  def update
    
  end

  def destroy
    @document = @folder.documents.find_by(id: params[:id])
    @document.destroy
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  private

    def correct_folder_and_documents
      @folder = @company.folders.find(params[:folder_id])
      @documents = @folder.documents
    end

    def document_params
      params.require(:document).permit(:file, :name)
    end

    def apikey
      @apikey = "14429e369be91199e238ed416a579a84"
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document_table_head.html.erb
<thead>
  <tr class="head-row">
    <th>Type</th>
    <th>Name</th>
    <th>Last Edited</th>
    <th>Created at</th>
    <th>Actions</th>
    <th>Size</th>
    <% if false %>
      <th>Download</th>
      <th>Edit</th>
      <% if current_user.role == "admin" %>
        <th>Delete</th>
      <% end %>
    <% end %>
  </tr>
</thead>

app/views/documents/_document_table_row.html.erb
<tbody>
  <tr class="body-row">
    <td><%= image_tag "#{document.file_content_type}" %></td>
    <td><%= document.name %></td>
    <% unless document.created_at.nil? || document.file_updated_at.nil? %>
      <span class="document-created-at">
      <td><%= document.created_at.strftime("%B %e, %Y") %></td>
      <td><%= document.file_updated_at.strftime("%B %e, %Y") %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
    <td>
    <% if true %>
    <!-- ACTIONS DROPDOWN -->
      <div class="btn-group folder-options-button">
        <button type="button" class="btn btn-default">Actions</button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
        <!-- View pdf or download link -->
          <% if document.file_content_type.include?("pdf") %>
            <li><%= link_to "View PDF", document.file.url(:original, false), target: "_blank" %></li>
          <% else %>
            <li><%= link_to "Download", document.file.url(:original, false), target: "_blank" %></li>
          <% end %>
          <!-- msword or excel edit with zoho -->
          <% if document.doc_or_spreadsheet? %>
            <li>
              <a href="#">
                <%= render 'documents/zoho_form', document: document %>
              </a>
            </li>
          <% end %>
          <!-- If admin, delete link -->
          <% if current_user.role == "admin" %>
            <li role="seperator" class="divider"></li>
            <li>
              <%= link_to folder_document_path(@folder, document), remote: true, class: "document-delete", method: :delete, data: { confirm: "Are you sure?"} do %>
              Delete
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </td>
    <td><%= number_to_human_size(document.file_file_size) %></td>
    <!-- Put these links in the dropdown or popover -->
  </tr>
</tbody>
<!-- Differentiate between admin and non-admin -->

app/views/documents/_document_upload_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="documentUploadModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Upload a document</h4>
        <div id="dropzone" class="fade">Drop files here</div>
        <span id="document-file-name"></span>
      </div>
      <%= form_for(@document, url: folder_documents_path(@folder), remote: true ) do |f|  %>
        <div class="modal-body">

          <!-- Fields -->
          <div class="form-group">
            <% f.label :name %>
            <% f.text_field :name, class: "form-control" %>
          </div>
          <div>
            <label class="btn btn-default btn-raised btn-file">
              <%= f.label :file, 'Browse' %>
              <%= f.file_field :file, name: "document[file]", onchange:"$('#upload-file-info').html($(this).val());" %><br>
              <!-- $('#documentUploadModal').modal('hide'); -->
            </label>
            <span class="label label-default" id="upload-file-info"></span>
          </div>

          <!-- Progress Bar -->
          <div class="progress-wrapper">
            <p>Bitrate: <span class="bitrate"></span></p>
            <div class="progress">
              <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                <span class="sr-only"></span>
              </div>
            </div>
          </div>
        </div>  

        <!-- Buttons -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-raised cancel-button" data-dismiss="modal">
            Close
          </button>

        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    var documentUploadForm = $('#new_document');

    documentUploadForm.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'),
      add: function (e, data) {
        types = /(\.|\/)(pdf|xls|xlsx|doc|docx)$/i;
        file = data.files[0]
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
          var name = file.name;
          $('#document-file-name').html(name);
        }
        else { alert(file.name + " must be XLS, XLSX, DOC, or DOCX file"); }
      }
    });

    documentUploadForm.on('fileuploadsubmit', function(e, data){
      data.formData = {'document[name]': data.files[0].name};
    });

    // Progress bar configuration
    var wrapper = documentUploadForm.find('.progress-wrapper');
    var progress_bar = wrapper.find('.progress-bar');

    documentUploadForm.on('fileuploadstart',function(){
      wrapper.show();
    });

    documentUploadForm.on('fileuploadaddone', function(){
      wrapper.hide();
      progress_bar.width(0); // Revert progress bar's width back to 0 for future upload
    });

    // Bit rate
    var bitrate = wrapper.find('.bitrate');

    // Complete progress bar with bitrate
    documentUploadForm.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(0) + 'Kb/s');

      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });

  });

  // Dropzone
  $(document).bind('dragover', function (e, data) {
    var dropZone = $('#dropzone'),
            timeout = window.dropZoneTimeout;
    if (!timeout) {
      dropZone.addClass('in');
    } else {
      clearTimeout(timeout);
    }
    var found = false,
            node = e.target;
    do {
      if (node === dropZone[0]) {
        found = true;
        break;
      }
      node = node.parentNode;
    } while (node != null);
    if (found) {
      dropZone.addClass('hover');
    } else {
      dropZone.removeClass('hover');
    }
    window.dropZoneTimeout = setTimeout(function () {
      window.dropZoneTimeout = null;
      dropZone.removeClass('in hover');
    }, 100);
  });
</script>

app/views/documents/_documents.html.erb
<div class="row">
  <div class="container-fluid">
  <h4 class="folder-title"><%= @folder.name %></h4>

  <% if current_user.role == "admin" %>
    <!-- Folder Options -->
    <div class="btn-group folder-options-button">
      <button type="button" class="btn btn-default">Folder Options</button>
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Permissions', '#' %></li>
        <li role="seperator" class="divider"></li>
        <li><%= link_to 'Delete Folder', folder_path(@folder), method: :delete, data: {confirm: "Are you sure you want to delete this folder?"}, class: "danger" %></li>
      </ul>
    </div>
    
  <% end %>
    <button type="button" class="btn btn-raised btn-success" id="document-upload-button" data-toggle="modal" data-target="#documentUploadModal">Upload File</button>
      <%= render 'documents/document_upload_modal' %>
   
  <table class="table" id="documentsTable">
    <%= render 'documents/document_table_head' %>
    <% if @documents.count > 0 %>
      <% @documents.each do |document| %>
        <% unless document.id == nil %>
          <%= render 'documents/document_table_row', document: document %>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div> 
</div>

app/views/documents/_zoho_form.html.erb
<form method="POST" action="<%= ZohoService.new(document).zoho_url %>" target="_blank" accept-charset="UTF-8">
  <%= hidden_field_tag "url", document.file.url %>
  <%= hidden_field_tag "apikey", "14429e369be91199e238ed416a579a84" %>
  <%= hidden_field_tag "output", "editor" %>
  <%= hidden_field_tag "mode", "normaledit" %>
  <%= hidden_field_tag "filename", document.file_file_name %>
  <%= hidden_field_tag "lang", "en" %>
  <%= hidden_field_tag "id", document.id %>
  <%= hidden_field_tag "format", document.file_format %>
  <%= hidden_field_tag "saveurl", root_url %>
  <%= submit_tag "Edit", class: "btn btn-default", style: "color: #ffffff;
    background: rgba(255, 255, 255, 0.01); padding: 0; border: 0; margin-top: -3px;" %>
</form>

app/views/documents/create.js.erb
<% if @document.new_record? %>
  alert('The file could not be uploaded: <%= j @document.errors.full_messages.join(', ').html_safe %>');
<% else %>
  $('#documentsTable').append("<%= j (render 'document_table_row', document: @document) %>");
<% end %>

app/views/documents/destroy.js.erb
$('#folder-window').html("<%= j (render 'documents') %>");

app/views/documents/edit.js.erb
$('#folder-window').html("<%= j (render 'zoho') %>");

app/views/documents/index.html.erb
<h1>Documents#index</h1>
<p>Find me in app/views/documents/index.html.erb</p>

app/views/documents/index.js.erb
$('#folder-window').html("<%= j (render 'documents') %>");