config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'folders#index'

  resources :company, only: [:show]
  resources :permissions, only: [:create, :destroy, :index]
  resources :comments, only: [:index, :create]
  
  resources :folders do
    resources :documents
  end
  
  delete 'delete_user/:id' => 'users#delete',        as: :delete_user
  get    'dashboard'       => 'dashboard#dashboard', as: :dashboard
  get    'settings'        => 'dashboard#settings',  as: :settings
  get    'users'           => 'users#index',         as: :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :projects
  has_many :folders
  has_many :documents, through: :folders
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :folder
  has_attached_file :file
  validates_attachment :file,
      styles: { thumb: "100x100#", small: "150x150#"},
      content_type: { content_type: [
        "application/pdf", "application/xls", "application/xlsx", 
        "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
        "application/msword", "application/doc",  
        "text/plain", "text/csv"]},
      message: "Sorry, only PDF, Excel, MSWord or plain text files are allowed."

  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user }

  def file_format
    content_type = self.file_content_type
    if content_type.include?("xlsx")
      return "xlsx"
    elsif content_type.include?("xls") || content_type.include?("excel")
      return "xls"
    elsif content_type.include?("spreadsheetml")
      return "ods"
    elsif content_type.include?("pdf")
      return "pdf"
    elsif content_type.include?("doc") || content_type.include?("msword")
      return "doc"
    elsif content_type.include?("text/plain") || content_type.include?("file/text")
      return "txt"
    elsif content_file = nil
      return "nil"
    end
  end

  def doc_or_spreadsheet?
    content_type = self.file_content_type
    if content_type.include?("xlsx") || content_type.include?("xls") || content_type.include?("excel") || content_type.include?("spreadsheetml") || content_type.include?("doc") || content_type.include?("msword")
      true
    else
      false
    end
  end

  # Permissions
  def can_be_accessed_by?(user)
    # the parent folder should have an attribute to track permitted users
    self.folder.can_be_accessed_by?(user)
  end

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :company
  has_many :permissions
  has_many :documents, dependent: :destroy

  def can_be_accessed_by?(user)
    if user.admin?
      true
    else
      self.permissions.find_by_user_id(user)
    end
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :folder
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Make confirmable?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company
  has_many :permissions
  has_many :comments
  has_attached_file :avatar
  validates_attachment :avatar,
      default_url: "avatars/:style/avatar_default.jpg",
      styles: { thumb: "100x100#", small: "150x150#", medium: "300x300#"},
      content_type: { content_type: [
        "image/jpg", "image/jpeg", "image/png", "image/gif"]},
      message: "Sorry, only png, gif, jpeg or jpg."
      
  

  enum role: [:normal, :admin]

  # For permissions, user should have attribute to hold folder ids that can be accessed
  # Maybe admins have a value of 0 for full access of folders?
  def can_access?(resource)
    resource.can_be_accessed_by?(self)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = current_user.comments.order('created_at DESC')
  end

  def create
    @comment = current_user.comments.build(comment_params)
    unless @comment.subject == "" || @comment.content == ""
      @comment.save
      if @comment.save
        redirect_to :back, notice: "Comment added"
      end
    else
      redirect_to :back, notice: "Subject or content cannot be empty."
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:subject, :content, :commented_page)
    end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  respond_to :html, :js
  def show
  end

  def files
  end

  def update
    
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  respond_to :html, :js

  def new
    @folder = @folders.build
  end

  def create
    @folder = @folders.build(folder_params)
    respond_to do |format|
      if @folder.save
        flash[:success] = "Folder successfuly created"
        format.html { redirect_to folders_path, folder: @folder }
      else
        flash[:danger] = "Folder not created."
        render action: 'new'
      end
    end
  end

  def show
    @folder = @folders.find(params[:id])
  end

  def index
    if params[:folder]
      @folder = @folders.find(params[:folder])
      @document = @folder.documents.build
      @documents = @folder.documents
    end
  end

  def destroy
    @folder = @folders.find_by(id: params[:id])
    @folder.destroy
    redirect_to folders_path
  end
  
  private

    def company_folders
      @folders = @company.folders
    end

    def folder_params
      params.require(:folder).permit(:name)
    end

    private
      # def accessible_folder
        
      # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_admin

  def index
    @permission = Permission.new
  end

  def delete
    @user = @users.find(params[:id])
    @user.destroy
    if @user.destroy 
      redirect_to users_path, notice: "User deleted"
    end
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Admin protections
  def admin_user?
    current_user.role == "admin" ? true : false
  end

  def redirect_if_not_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end

  def redirect_unless_admin_user
    redirect_to(root_url) unless current_user.role == "admin"
  end

  # Comments
  def current_comment
    if user_signed_in?
      @comment = current_user.comments.build
    end 
  end

  # Company down instance variables
  def current_company
    if user_signed_in?
      @company = current_user.company
      @folders = @company.folders
      if current_user.admin?
        # excluding self
        @users = @company.users
      end
    end
  end

  # VIEWS  
  def disable_sidebar
    @disable_sidebar = true
  end

  # Formating
  def prettify(amount)
    number_to_currency(amount, unit: "", separator: ".", delimiter: ",", significant: false)
  end
  
  def full_title(page_title = '')
    base_title = "Trust Construction"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_comment_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="commentModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      Add Comment
      </div>
      <div class="modal-body">
        <%= form_for(@comment, url: comments_path(current_user)) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <% f.label :commented_page %>
          <% f.text_field :commented_page, value: request.original_url %>

          <%= f.label :subject %>
          <%= f.text_field :subject, class: 'form-control' %>

          <%= f.label :comment %>
          <%= f.text_area :content, class: 'form-control' %>
        
      </div>
      <div class="modal-footer">
          <%= f.submit "Add Comment", class: "btn btn-primary form-control" %>
        <% end %>
      </div>
    </div>
  </div>
</div> 

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>

  <% if message_type == "alert" %>
    <div class="alert alert-danger alert-dismissible">
  <% elsif message_type == "notice" %>
    <div class="alert alert-info alert-dismissible">
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible">
  <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= render 'layouts/comment_modal' %>
    <% end %>
    <!-- Remaining content -->
      <div id="content">
        <div class="container-fluid">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
  <% else %>
  <!-- When not signed in -->
    <%= yield %>
  <% end %>
</body>
</html>

app/views/shared/_activities.html.erb
<div class="">
  <ul class="list-group">
    <%= render_activities @activities %>
  </ul>
</div>



<!-- For use with i18n, but only after fixing the scss @extend issue -->
<% if false %>

<div class="">
  <ul class="list-group">
    <% @activities.each do |activity| %>
      <li class="list-group-item">
        <span class="glyphicon glyphicon-<%= activity.key.match(/\.(.*)/)[1] %>"></span>
        <strong><%= activity.owner ? activity.owner.first_name : 'Guest' %></strong>
        <%= render_activity activity, display: :i18n %>
        <% if activity.trackable %>
          "<span class="activity-file-name"><%= activity.trackable.name %></span>"
        <% else %>
          with unknown title.
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="main-navbar" role="navigation" style="margin-bottom: 0">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <div class="brand-header">Trust Construction</div>
      <% end %>
    </div>

    <!-- For toggling collapsible navmenu -->
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Folders", folders_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to 'Dashboard', dashboard_path %></li>
            <li><%= link_to "Manage Users", users_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user.admin? %>
            <li>
              <a href="#" id="add-comment-button" data-toggle="modal" data-target="#commentModal">Add Comment</a>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false"><%= "#{current_user.first_name} #{current_user.last_name}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li><%= link_to 'Comments', comments_path(current_user) %></li>
              <% end %>
              <li><%= link_to 'Settings', settings_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      <% else %>
        <div class="navbar-right">
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-raised btn-success navbar-btn" %>
          <%= link_to 'Log In', user_session_path, class: "btn btn-raised btn-success navbar-btn btn-right" %>
        </div>
      <% end %>
    </div>

  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<div class="nav-side-menu">
  <!-- Logo -->
  

  <div class="menu-list">
    <ul id="menu-content" class="menu-content collapse out">
    
      <!-- Home -->
        <li>
          <%= link_to root_path do %>
            <i class="material-icons sidebar-icon">home</i> <span class="sidebar-label">Home</span>
          <% end %>
        </li>

      <% if false #@folder_view %>
        <% @folders.each do |folder| %>
          <li role="presentation" class="folder-button"><%= link_to folder.name, folder_documents_path(folder), remote: true %></li>
        <% end %>
        <li role="presentation" class="new-folder-button" ><%= link_to "Create new folder", new_folder_path, remote: true%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar_button.html.erb
<a href="#" class="toggle-sidebar sidebar-closed" id="sidebar-toggle"><i class="material-icons md-36" data-toggle="collapse" data-target="#menu-content">menu</i></a>